### PR TITLE
Add routePersistence parameter to Page::resolveMenuItem()

### PR DESCRIPTION
**Pull request by mjauvin**
This permits reusing Cms Page resolveMenuItem with or without route persistence for the call to pageUrl().

The default behavior is unchanged as we default to false for route persistence.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Can you provide your usage example here along with why you needed routePersistence enabled for your use case?

**Comment by mjauvin** [comment]
@LukeTowers On the `Project` sub-section of this website, the menubar changes and all pages depend on the project slug, so their `url` is `project/:slug/page` (e.g. `project/:slug/about`, `project/:slug/team`, etc.)

In order to render the menu for those pages, the slug in their url needs to inherit the project slug, hence the route persistence.

**Comment by mjauvin** [comment]
With this PR, I can use the following in my component:
```php
Event::listen('pages.menuitem.resolveItem', function ($type, $item, $url, $theme) {
    if ($type === 'cms-page' && str_starts_with($item->reference, 'project/')) {
        return \Cms\Classes\Page::resolveMenuItem($item, $url, $theme, true);
    }
}, 10000);
```

**Comment by mjauvin** [comment]
Without this PR, I need to duplicate the resolveMenuItem method in my component.

**Pull request merged**
