### PR TITLE
[WIP] Icon font update

### PR DESCRIPTION
**Pull request by WebVPF**
This pull request updates FontAwesome icons from version 4.7.0 to 6.0.0

## Icons

Original:

```css
.fa-snowflake::before {content:"\f2dc"}
```

For Winter CMS:

```css
.wn-icon-snowflake::before,
.oc-icon-snowflake::before,
.icon-snowflake::before {content:"\f2dc"}
```

## Brands icons:

Original:

```css
.fa-github:before {content:"\f09b"}
```

For Winter CMS:

```css
.wn-icon-github:before,
.oc-icon-github:before,
.icon-github:before {content:"\f09b";font-family:'FontAwesome Brands'}
```

## Compatibility

There is no full support for old icons. Many old icons are supported, but some are not.

Example FA-4.7.0 `fa-snowflake-o` => FA-6.x `fa-snowflake`

<a href="https://gitpod.io/#https://github.com/wintercms/winter/pull/445"></a>

### CODE REVIEW

**Comment by LukeTowers** [comment]
Hmm, this seems like it could be a breaking change. Are you able to list out all of the breaking changes and any ideas for smoothing over them?

**Comment by LukeTowers** [comment]
Also what's the main benefit to the project of performing this upgrade in the first place?

**Comment by WebVPF** [comment]
> Hmm, this seems like it could be a breaking change. Are you able to list out all of the breaking changes and any ideas for smoothing over them?

There are no breaking changes in this pull request. We're just updating the CSS to expand the icon library.
All old icons are supported. There will be no problems.

Some of the icons have been redrawn by the authors of the library.

The only problem that may be is to include new styles in the documentation page with the icon library.

---

There is a change that changes styles. Here it is:

It was:
https://github.com/wintercms/winter/blob/cf5ae34f5adfa17f18d7f8f381a2fc73330b744a/modules/system/assets/ui/storm.css#L4117

It became:
```css
.icon-lg {font-size:1.25em;line-height:0.05em;vertical-align:-0.075em}
```

I don't think it's critical. But if necessary, you can return the old value.

### LESS

The `storm.less` file has been deprecated for 3 years now. Changes are made directly to the `storm.css` file.
I have removed the `less` files associated with the old icons so that they are not misleading in the future.

### Questions I have:

- What to do with the CSS animations that come with the new icon font? Remove or keep?
- Documentation. Connect CSS style for new icons to documentation page.

**Comment by WebVPF** [comment]
> Also what's the main benefit to the project of performing this upgrade in the first place?

@LukeTowers Icons are an integral part of the interface.
For a programmer, code is important, not icons. And for a user who will use the administrative part (redactors, managers, etc.), it will be nice that the site has a modern icon library, and not outdated.

FontAwesome 4.7.0 - 675 icons
FontAwesome 6.0.0 - 1748 icons

**Comment by LukeTowers** [comment]
@WebVPF `storm.less` is not deprecated, you compile it by running `winter:util compile less`. We have to keep those files around (since people may have been including them directly in their own less stacks), so is it possible to replicate them targeting v6 so we don't have any issues with that?

The `icon-lg` change is fine, we can always revert that if someone complains.

What's the file size difference between the old icon library and the new one? That's going to have an impact on everyone so it's important we look at that too.

**Comment by WebVPF** [comment]
> What's the file size difference between the old icon library and the new one? That's going to have an impact on everyone so it's important we look at that too.

Old file `storm.css` - 356 KB
New file `storm.css` - 520 KB

After deleting comments, empty lines, line breaks, spaces, the `storm.css`-file will be less than 500 KB

---

Fonts:
- fa-brands-400.ttf - 176 KB
- fa-brands-400.woff2 - 103 KB
- fa-regular-400.ttf - 59 KB
- fa-regular-400.woff2 - 24 KB
- fa-solid-900.ttf - 297 KB
- fa-solid-900.woff2 - 124 KB

**Comment by LukeTowers** [comment]
@WebVPF I'm not opposed to merging this in, are you no longer interested in finishing it?

**Pull request closed without merging**
