### PR TITLE
Updated jquery to 3.6.0, jquery migrate to 3.3.2

### PR DESCRIPTION
**Pull request by koesper**
The jQuery version for the backend still contained a patched version of 3.4.0. This updates jquery and the combined files to 3.6.0. jQuery Migrate is also updated

### CODE REVIEW

**Comment by LukeTowers** [comment]
Thanks for this @koesper, could you also submit a PR to the docs wherever we mention the currently included version of jQuery?

**Comment by arvislacis** [comment]
@koesper @LukeTowers This probably needs to be revised and updated (maybe before actual merge) because the newest version of jQuery now is 3.7.0.

**Comment by koesper** [comment]
Thanks @arvislacis, just pushed the updates. Perhaps @LukeTowers can merge them in?

**Comment by LukeTowers** [comment]
@koesper can you pull in the latest again and I'll merge it for 1.2.5

**Comment by koesper** [comment]
@LukeTowers hope this works for you? seemed like the cleanest solution to do it in a clean fork & PR.
Also updated the documentation in https://github.com/wintercms/docs/pull/167

**Pull request closed without merging**
