### PR TITLE
Update EditorConfig link

### PR DESCRIPTION
**Pull request by WebVPF**
This is a useful extension that should be recommended to users who do not have it installed.
https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

### CODE REVIEW

**Comment by bennothommo** [comment]
I think my only hesitation on including this is that I don't want to enforce a coding style on people writing their own projects. We use `.editorconfig` mainly to enforce standards on development of the core itself. The EditorConfig extension, I've found, can be a pain if you need to make a change that doesn't follow the rules - for example, some test cases needed a file that had no final newline, but EditorConfig kept adding it in, so in the end, I had to disable the extension.

@wintercms/maintainers any thoughts on this?

**Comment by LukeTowers** [comment]
What's the UX for this? VSCode just asks if you want to install recommended extensions?

**Comment by bennothommo** [comment]
@LukeTowers that's correct.

**Comment by WebVPF** [comment]
Ben is right. The recommendation has been removed.

**Pull request merged**
