### PR TITLE
Pluralize the number of items in a folder

### PR DESCRIPTION
**Pull request by WebVPF**
It's in the media manager. Here:

screen-media

### CODE REVIEW

**Comment by WebVPF** [comment]
Also fixed icon for `Return to the parent folder`

**Comment by WebVPF** [comment]
@LukeTowers What is wrong with this PR?

**Comment by LukeTowers** [comment]
@WebVPF hadn't had a chance to look yet. Do you have a screenshot of the end result?

**Comment by WebVPF** [comment]
@LukeTowers  This is what it looks like now:







After the change:



Icon changed to only link to parent folder

**Comment by WebVPF** [comment]
Endings in Russian can be seen well

**Comment by LukeTowers** [comment]
Is it supposed to still say item(s)?

**Comment by WebVPF** [comment]
@LukeTowers

**Review by LukeTowers — APPROVED** [review]

**Comment by LukeTowers** [comment]
Great job @WebVPF, thanks! It's a small quality of life improvement but it's just one of those nice to have bits of polish that ties everything together more and makes the project as a whole feel more fleshed out and professional :)

Keep up the great work!

**Pull request merged**
