### PR TITLE
Change password reset messaging to remove user not found

### LINKED ISSUE #32: Improve password reset validation
Refs: octobercms/october#5516

### PR DESCRIPTION
**Pull request by dhawton**
Removes messaging about user not being found during password reset requests. Resolves #32

### CODE REVIEW

**Comment by bennothommo** [comment]
@dhawton Fix seems to be good, but I wonder if we need to adjust the `backend::lang.account.restore_success` lang string to say something along the lines of: "If your account exists, an email has been sent to your inbox with reset instructions."?

**Comment by dhawton** [comment]
English done, need to source native speakers for the other languages to convert those.

**Comment by LukeTowers** [comment]
@dhawton if you could change it to @bennothommo's suggestion, that's way better than mine :)

**Comment by dhawton** [comment]
@LukeTowers Done.

**Pull request merged**
