### PR TITLE
Move after login logic to event listener instead of controller

### PR DESCRIPTION
**Pull request by mjauvin**
User model now handles running the migrations in its afterLogin() method.

### CODE REVIEW

**Comment by bennothommo** [comment]
This is burying that sort of functionality deep, in a place I wouldn't think to look if I was looking for it.

Could we not just add a listener in the Backend's service provider for the `backend.user.login` event and just fire the functionality there?

Or even better, begone with it completely. Migrations should be explicitly run via an action (installing plugins, running the console command) - not arbitrarily when logging in.

**Comment by mjauvin** [comment]
> This is burying that sort of functionality deep, in a place I wouldn't think to look if I was looking for it.

That's why they invented "grep"! :stuck_out_tongue_closed_eyes: 

> Could we not just add a listener in the Backend's service provider for the `backend.user.login` event and just fire the functionality there?

I don't mind, as long as we all agree.

> Or even better, begone with it completely. Migrations should be explicitly run via an action (installing plugins, running the console command) - not arbitrarily when logging in.

The main reason to keep the functionality is for users without shell access: they can run the migrations just by login into the backend.

Personally, I don't care about this feature.

**Comment by LukeTowers** [comment]
Let's move it to the service provider in an event listener for now with the eventual plan to remove it once we have the updates / installation system working more reliably and consistently.

**Comment by mjauvin** [comment]
How's that?

**Review by LukeTowers — APPROVED** [review]

**Pull request merged**
