### PR TITLE
Add redirect

### PR DESCRIPTION
**Pull request by WebVPF**
Winter CMS generates a duplicate of the home page.

Example: 
https://wintercms.com
https://wintercms.com/index.php

<a href="https://gitpod.io/#https://github.com/wintercms/winter/pull/390"></a>

### CODE REVIEW

**Comment by LukeTowers** [comment]
Does this work even for installs in sub folders?

**Comment by WebVPF** [comment]
Yes. The rule for the main page of the installation.
From the page `/index.php` will redirect to the page `/`

Let @bennothommo watch. Maybe he knows better the solution.
I have shown an example of a duplicate.

**Comment by WebVPF** [comment]
I am sorry. My server has been cached.
```
Redirect 301 /index.php /
```

**Comment by WebVPF** [comment]
I am sorry. My server has been cached.

This:

```
Redirect 301 /index.php /
```

causes an infinite redirect

**Comment by WebVPF** [comment]
There is such a solution:

```apacheconf
RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
RewriteRule (.*?)index\.php/*(.*) /$1$2 [R=301,NE,L]
```

This is working correctly.

**Pull request closed without merging**
