### PR TITLE
Update Farsi language

### PR DESCRIPTION
**Pull request by rezalaal**
Update new items on Validation.php Farsi language file

### CODE REVIEW

**Comment by rezalaal** [comment]
Update new items on Validation.php Farsi language file

**Comment by LukeTowers** [comment]
All of these should be a single PR

**Comment by rezalaal** [comment]
Means I must send PR again with One commit?

**Comment by LukeTowers** [comment]
@rezalaal what you should do is merge all of your patch-* branches into a single branch in your forked copy on your account and then submit a PR based off of that single branch.

**Pull request closed without merging**
