### PR TITLE
Add inputmode attribute to datepicker formwidget

### PR DESCRIPTION
**Pull request by mjauvin**
On mobile, when the DatePicker formwidget opens, you don't want the keyboard to popup.

In order to prevent this behavior, we add inputmode=none to the input field. (ref. https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/#aa-none)

This can still be overriden in the field config like this:
```
date:
    type: datepicker
    attributes:
      inputmode: text
```

### CODE REVIEW

**Comment by bennothommo** [comment]
@mjauvin I'm going to bump this to v1.2.3 as v1.2.2 is locked from further issues/PRs so that we can get it out the door. :)

**Comment by mjauvin** [comment]
What about these errors @bennothommo ?

**Comment by bennothommo** [comment]
Probably just needs to be re-run. Doing that now :)

EDIT: This branch needs to pull in the changes from `develop` to fix the issue.

**Comment by LukeTowers** [comment]
@mjauvin the only concern I have with this is if the datepicker widget fails to load. Perhaps we could instead set the attribute as the final step of the datepicker initializing so that it will only take effect when we know that the datepicker JS will be able to handle the date selection before we prevent the users from being able to enter data manually?

**Comment by mjauvin** [comment]
An alternative would be to simply document this and let people enable this themselves?

But frankly, most if not all our formwidgets would be broken if their js didn't load/run

**Comment by LukeTowers** [comment]
Not necessarily, it's happened before that only specific widgets broke 😜.

**Comment by bennothommo** [comment]
@mjauvin still need something like what @LukeTowers [suggested](https://github.com/wintercms/winter/pull/891#issuecomment-1529155407) to be implemented. I agree most widgets would not work with JS, but where we can, we should gracefully degrade.

**Comment by mjauvin** [comment]
Allright, hope this is satisfactory now!

**Comment by LukeTowers** [comment]
@mjauvin any chance you could provide a before / after screen recording?

**Comment by mjauvin** [comment]
Are you serious?

Before: when you click on a date/time picker field, the keyboard pops up along with the date/time selector

After: only the date/time selector pops up.

**Comment by LukeTowers** [comment]
@mjauvin I understand that, I just want verification that the JS approach works correctly 😜

**Comment by mjauvin** [comment]
> @mjauvin I understand that, I just want verification that the JS approach works correctly stuck_out_tongue_winking_eye

It works, I tested it.

**Comment by LukeTowers** [comment]
Good enough for me :P

**Comment by LukeTowers** [comment]
Will merge after releasing 1.2.2

**Pull request merged**
