### PR TITLE
Added soft deleting to Backend User Groups

### PR DESCRIPTION
**Pull request by arvislacis**
Tries to solve https://github.com/wintercms/winter/issues/386

Depends on https://github.com/wintercms/storm/pull/156 PR

### CODE REVIEW

**Comment by mjauvin** [comment]
softDelete option should not be added to the UserGroup model relation, only to User model relation

**Comment by arvislacis** [comment]
@mjauvin Removed/reverted `softDelete` from `UserGroup` model.

**Comment by arvislacis** [comment]
Waiting for https://github.com/wintercms/storm/pull/156 to be merged.

**Comment by mjauvin** [comment]
@arvislacis can you test if applying this PR properly fixes the issue with Storm's develop branch? @LukeTowers or @bennothommo will merge this if it does.

**Comment by arvislacis** [comment]
@mjauvin Yes, I can confirm that applying this PR and the latest changes from winter/storm develop branch fixes the issue.

**Comment by mjauvin** [comment]
@bennothommo @LukeTowers we can merge this one and close its associated issue (https://github.com/wintercms/winter/issues/386)

**Pull request merged**
