### PR TITLE
[WIP] implementation for winter:lang console command

### PR DESCRIPTION
**Pull request by mjauvin**
php artisan winter:lang [module] [langFile] [targetLocale]

### CODE REVIEW

**Comment by LukeTowers** [comment]
@larrybarker did you have a console command to identify missing keys from one locale to another?

**Comment by LukeTowers** [comment]
@mjauvin please provide a detailed description of the functionality provided by the command and any arguments & options

**Comment by LukeTowers** [comment]
Not 100% sure this will be an ideal fit for the core, could be useful in the winter CLI tool though. I'll wait to see a description of functionality before we make that call though.

**Comment by mjauvin** [comment]
I'll probably end-up adding it to my YAMLocalizer plugin @LukeTowers

**Comment by mjauvin** [comment]
Moving this to [YAMLocalizer plugin](https://github.com/mjauvin/wn-localize-plugin).

**Pull request closed without merging**
