### PR TITLE
Composer dependency updates for Laravel 9 support

### PR DESCRIPTION
**Pull request by tschallacka**
Pulled current develop branch into wip/1.2 to bring wip/1.2 up to date with the current status

### Modified [composer.json](composer.json).

Referenced storm/wip/1.2 for storm dependency     
Referenced wip/1.2 for the modules backend, cms, and system. This needs to be altered when work in progress becomes final.  
Altered Laravel dependency to ~9.0
Set minimum PHP version to 7.4

### Modified [modules/backend/composer.json](modules/backend/composer.json), [modules/cms/composer.json](modules/system/composer.json), [modules/system/composer.json](modules/system/composer.json)

Altered Laravel dependency to ~9.0
Set minimum PHP version to 7.4

Updating the WIP branches as discussed here https://github.com/wintercms/winter/pull/148#issuecomment-840148294 would be greatly appreciated :-)

<a href="https://gitpod.io/#https://github.com/wintercms/winter/pull/172"></a>

### CODE REVIEW

**Comment by LukeTowers** [comment]
@tschallacka 9.0 isn't out yet so we'll need to target the same version as the Storm library in 1.2, and then once 9.0 is out and we're ready to release 1.2 we can switch it back to 9.0

**Comment by tschallacka** [comment]
@LukeTowers My bad, fixed now with the same version that's in the storm library.

**Comment by LukeTowers** [comment]
@tschallacka is Laravel 9 going to be requiring minimum of PHP 8 now?

**Comment by tschallacka** [comment]
@LukeTowers https://github.com/laravel/laravel/blob/77086029af21522a87af3c44e3b945cd02618f79/composer.json#L8

**Comment by LukeTowers** [comment]
@tschallacka could you bump it in the winter & storm repo PRs?

**Comment by tschallacka** [comment]
@LukeTowers  I assume you mean the upgrade to nine branch, thats already done https://github.com/wintercms/storm/pull/26/commits/e59b50aa259322871c17f33a71f87c76603fa1a1#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R46

**Comment by tschallacka** [comment]
Laravel has pushed its newest major release to 2022. https://laravel-news.com/laravel-9

Php8 & symfony 6

Maybe rename/move these commits to a laravel 9 branch so winter can push out an minor update in the long wait?

**Comment by LukeTowers** [comment]
@tschallacka we still are pushing minor updates, 1.2 is not blocking 1.1.*, our free time is doing that 😉

**Pull request closed without merging**
