### PR TITLE
Add instructions for extending allowed file types

### PR DESCRIPTION
**Pull request by damsfx**

### CODE REVIEW

**Comment by bennothommo** [comment]
@damsfx this might be better being put into the docs rather than cluttering up the config, if it's not already in there. Thoughts?

**Comment by damsfx** [comment]
@bennothommo Yes, that might be a better location, but as a developer, I like to get the information as soon as possible.  
On the other hand, I'm a bit lost now, I don't really know in which branch of the documentation to propose this modification.

**Comment by LukeTowers** [comment]
@damsfx you can make the change in the develop branch. As far as what page it should be on, probably tie it to the fileupload field and maybe the mediamanager?

**Comment by damsfx** [comment]
@LukeTowers @bennothommo How about putting it in the `setup/configuration` section and linking to it from the `backend/forms/file-upload` and `cms/mediamanager` pages?

**Comment by LukeTowers** [comment]
Sounds perfect @damsfx

**Comment by damsfx** [comment]
> Sounds perfect @damsfx

@LukeTowers I think this PR can be closed in favour of the one submitted for documentation https://github.com/wintercms/docs/pull/178 .

**Comment by bennothommo** [comment]
Closed in favour of https://github.com/wintercms/docs/pull/178

**Pull request closed without merging**
