### PR TITLE
Scaffolding Improvements

### PR DESCRIPTION
**Pull request by LukeTowers**
There have been a number of improvements to the Laravel Scaffolding commands since the last time they were synced (probably around Laravel 5.1). This PR aims to pull in as many additional scaffolding commands as makes sense for Winter and provides aliases for the existing scaffolding commands (i.e. `create:controller` also accessible as `make:controller`) while also supporting as many of the arguments / options of the original Laravel scaffolding commands to improve the developer experience.

Requires https://github.com/wintercms/storm/pull/76

On a somewhat related note, would like to add a command to clear the resized directory: https://github.com/wintercms/winter/pull/178

<a href="https://gitpod.io/#https://github.com/wintercms/winter/pull/486"></a>

Replaces / Resolves:
- https://github.com/octobercms/library/pull/487
- https://github.com/wintercms/storm/pull/35
- https://github.com/wintercms/winter/discussions/201
- https://github.com/wintercms/storm/pull/36

### CODE REVIEW

**Comment by LukeTowers** [comment]
This is a Draft PR FYI.

**Comment by mjauvin** [comment]
@LukeTowers how close are we to merge this, I would find it really useful RIGHT NOW! ;)

**Comment by LukeTowers** [comment]
Test it out, I believe there's still some work to do for it to bring it more in line with Laravel and then testing and bugfixing.

**Comment by LukeTowers** [comment]
Still a few todo items but I've added them to the main comment on the Laravel 9 PR to be dealt with later so that we can start using the work that exists on this so far.

**Pull request merged**
