### PR TITLE
Allow scoped and local extensions on core controllers.

### PR DESCRIPTION
**Pull request by mjauvin**
Complement https://github.com/wintercms/storm/pull/134

### CODE REVIEW

**Comment by mjauvin** [comment]
the `__call()` and `__callStatic()` methods could also be added to `ExtendableTrait`, not sure if this is a good idea though.

**Comment by LukeTowers** [comment]
Traits can't have magic methods AFAIK which is why they aren't there already.

**Comment by LukeTowers** [comment]
Is this taking into account the existing __call & __callStatic methods on these classes / their parents?

**Comment by mjauvin** [comment]
> Is this taking into account the existing __call & __callStatic methods on these classes / their parents?

It is in ExtendableTrait's `extendableCall()` & `extendableCallStatic()` methods.

**Comment by LukeTowers** [comment]
@mjauvin I mean this PR is going to overwrite the existing base class' __call() and __callStatic() methods, we need to make sure the behavior remains the same.

**Comment by mjauvin** [comment]
@LukeTowers I adjusted CmsController & BackendController's `__call()` method to replicate the previous behavior.

What should we do for the the `__callStatic()` methods of the same two classes which previously did not exist ? Throw a badMethodCall exception  like below?
```php
    public static function __callStatic($name, $params)
    {   
        if ($name === 'extend') {
            if (empty($params[0])) {
                throw new \InvalidArgumentException('The extend() method requires a callback parameter or closure.');
            }
            self::extendableExtendCallback($params[0], $params[1] ?? false, $params[2] ?? null);
            return;
        }
        
        throw new BadMethodCallException(sprintf(
            'Method %s::%s does not exist.', static::class, $method
        ));
    }
```

**Comment by mjauvin** [comment]
Looking into this again, and the behavior is not changed without calling the parent's `__call()` / `__callStatic()` methods. If we don't call the ExtendableTrait's methods (extendableCall() and extendableCallStatic()), we loose the extensibility (other than the "extend()" method itself).

What do you think @bennothommo ?

**Comment by mjauvin** [comment]
The base class for CmsController & BackendController is Illuminate\Routing\Controller which has no special handling other than returning BadMethodCallException().

So behavior will not change.

**Review by bennothommo — APPROVED** [review]
As far as I can tell, this should be OK. I had to do the same thing for the database models.

**Comment by LukeTowers** [comment]
Does it still throw the exact same BadMethodCall Exception if the resolution fails?

**Comment by mjauvin** [comment]
> Does it still throw the exact same BadMethodCall Exception if the resolution fails?

Depends which class and whether it's static or not...

Backend\Classes\Controller throws the exact same exception.

Backend\Classes\BackendController & Cms\Classes\CmsController used to throw a php Error exception since they didn't have any `__callStatic()` method defined, now they will throw the same BadMethodCall exception. Also, their `__call()` method will now thrown the same exception as before (BadMethodException), but the error message is slightly different: "Call to undefined method %s::%s()" vs "Method %s::%s does not exist."

**Pull request merged**
