### PR TITLE
Add configuration attribute to force showing an empty repeater form a…

### PR DESCRIPTION
**Pull request by lex0r**
…utomatically if there are no existing repeater items yet.

### CODE REVIEW

**Comment by lex0r** [comment]
See https://github.com/wintercms/winter/issues/448

**Comment by LukeTowers** [comment]
You should be able to accomplish the same end result in user space right now by setting the value of the attribute to an array with one empty array inside of it.

Something like this:

```php
Event::listen('backend.form.extendFields', function ($formWidget) {
    // Check that we're extending the correct Form widget instance
    if (
        !($formWidget->getController() instanceof \Winter\User\Controllers\Users)
        || !($formWidget->model instanceof \Winter\User\Models\User)
        || $formWidget->isNested
    ) {
        return;
    }

    if (empty($widget->model->my_attribute) && empty($widget->data->my_attribute)) {
        $widget->data->my_attribute = [[]];
    }
});
```

**Comment by lex0r** [comment]
@LukeTowers do you think it's better to use the solution you suggested or make the widget's behaviour more explicit and understandable to users?

**Comment by LukeTowers** [comment]
I'm not opposed to making the FormWidget's behaviour more explicit and understandable but I'm not a fan of the proposed implementation as it sits right now. `showEmpty` isn't clear to me what exactly it does and having a configuration value that then just applies a client side "hack" of clicking a button using JS isn't a great experience.

Do you have any alternative suggestions for an interface / configuration property that might be more clear / intuitive for developers that are trying to accomplish what you propose; alternatively do you have more to say about why your proposed option is the best one?

**Comment by lex0r** [comment]
Naming is a notoriously difficult problems in software development :)

My solution is not the best one, it just does the job. Definitely can be improved, so anyone willing to do so is welcome.

**Comment by LukeTowers** [comment]
> Naming is a notoriously difficult problems in software development :)
> 
> My solution is not the best one, it just does the job. Definitely can be improved, so anyone willing to do so is welcome.

Then in that case I guess my answer to the original question of "do you think it's better to use the solution you suggested" is "yes, unless you or anyone else can propose a better API / developer experience" 😜 For anyone's future reference looking to do something similar:

```php
Event::listen('backend.form.extendFields', function ($formWidget) {
    // Check that we're extending the correct Form widget instance
    if (
        !($formWidget->getController() instanceof \Winter\User\Controllers\Users)
        || !($formWidget->model instanceof \Winter\User\Models\User)
        || $formWidget->isNested
    ) {
        return;
    }

    // Ensure that there is always at least one item ready to be populated
    if (empty($widget->model->my_attribute) && empty($widget->data->my_attribute)) {
        $widget->data->my_attribute = [[]];
    }
});
```

**Pull request closed without merging**
