### PR TITLE
Put mail template style tags in the head

### PR DESCRIPTION
**Pull request by RomainMazB**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Out of curiosity was the old location causing any issues?

**Comment by mjauvin** [comment]
Technically, style tag have to be within the head tag... Strict mail client might not honor it within the body tag.

**Comment by LukeTowers** [comment]
Fair enough, I'm just wondering if there any real world issues with it. Not opposed to merging, just wondering if there was a real world issue that prompted this because there wasn't anything in the PR description.

**Comment by RomainMazB** [comment]
Nope @LukeTowers , I did not see any issue, I just worked on some mail layout and figured out it was misplaced.

**Comment by LukeTowers** [comment]
According to https://www.campaignmonitor.com/css/style-element/style-in-body/ vs https://www.campaignmonitor.com/css/style-element/style-in-head; putting it in the head has slightly better support across some gmail clients, but loses support for yahoo mail on android. Works for me :)

**Pull request merged**
