### PR TITLE
Restore full Laravel Mailer behavior

### PR DESCRIPTION
**Pull request by mjauvin**
Related to https://github.com/wintercms/storm/pull/7

<a href="https://gitpod.io/#https://github.com/wintercms/winter/pull/45"></a>

### CODE REVIEW

**Comment by mjauvin** [comment]
Note: I merged the `wip/version-yaml-processing` branch to make tests pass.

**Comment by LukeTowers** [comment]
@mjauvin are there any breaking changes in this?

**Comment by mjauvin** [comment]
> @mjauvin are there any breaking changes in this?

@LukeTowers No, it just add missing functionality from Laravel.

**Comment by bennothommo** [comment]
Looks fine to me - we just need to test it.

**Comment by mjauvin** [comment]
@LukeTowers is it possible to apply this PR against wip/1.2 instead of develop?

**Pull request closed without merging**
