### PR TITLE
Updating Winter's branding colors

### PR DESCRIPTION
**Pull request by HitArrowLegend**
Updating all the @brand variables to match the new color chart.

### CODE REVIEW

**Comment by bennothommo** [comment]
@HitArrowLegend thanks for this. Just for easy review, would you mind taking some screenshots of various elements with these colours applied?

**Comment by LukeTowers** [comment]
Also if you could run `php artisan winter:util compile less` locally and commit the generated files that'd be great too :)

**Comment by HitArrowLegend** [comment]
I'm finishing updating all the files. I'm doing them one by one so it takes some time. I'll add screenshots once I'm totally done (and I'll add the compiled css too)

**Comment by HitArrowLegend** [comment]
About screenshots: 

Image
Image
Image
Image
Image
Image
Image
Image

The "new" icons are just a recolorisation to match the rest of the colors. Overall it's less Orange everywhere.

About ServiceProvider.php and reportcontainer.less, they are now being correctly added to the main theme with these changes.

**Comment by bennothommo** [comment]
@HitArrowLegend looking good so far. Just a couple of points of feedback:

- The color for the primary buttons is too bright and "muted". It should be the stronger blue.
- Not the biggest fan of the green background for dropdown and list hover states. I think that needs to be the light blue instead.

**Comment by HitArrowLegend** [comment]
I'll switch colors for buttons. When you mean stronger blue, do you mean the dark blue from the sidebar ?

About the green vs blue, I thought that too but did it anyway because originally, ocms was using its Brand accent (which is blue #3498db), and for this variable, i picked the lime green from your color chart. 
I'll switch it to something else tho.

**Comment by HitArrowLegend** [comment]
Is it more to your liking ? 

https://puu.sh/Hwu98/534f97a671.png

**Comment by bennothommo** [comment]
@HitArrowLegend yeah that's better. Are you able to use the same for the selected media item as well? :)

**Comment by HitArrowLegend** [comment]
yeah of course; I'll update it now then

**Comment by bennothommo** [comment]
@HitArrowLegend is this work completed on your end?

**Comment by LukeTowers** [comment]
Replaced by #93

**Pull request closed without merging**
