### PR TITLE
Correctly handle arrayed POST data in AJAX calls

### LINKED ISSUE #683: [v1.2] CMS editor doesn't save all components added to page/layout/etc
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Pages

### Issue description

Adding multiple components to a layout/page from the CMS editor does not work, and only the last added component is saved to the actual file itself. All other components are lost.

### Steps to replicate

1. Install fresh winter cms project
2. Install Winter.Pages plugin
3. Add `static page` and `static menu` components to the default layout.
4. Save
5. View the `layouts/default.htm` file from your IDE/editor and see only one component is actually saved to the file.

### Workaround

Add components manually from your editor/IDE without using the backend.

### PR DESCRIPTION
**Pull request by bennothommo**
The changes introduced in https://github.com/wintercms/winter/commit/a4cfd0d23f4342f530dc4b425098ee24086cd8d1 have broken arrayed POST values, as the original `serializeFormToObj` method that converts the form data to an object overwrites values with the same key, which includes arrayed data (ie. a field with `name[]` and value `foo` will be overwritten by a following field `name[]` and value `bar` - only `bar` will remain in the object)

This fix leverages the `FormData` class to correctly send back arrayed POST data as part of its `entries` loop, and saves the data as an array as necessary.

Fixes https://github.com/wintercms/winter/issues/683.
Will also fix the issue reported here: https://github.com/wintercms/winter/issues/683#issuecomment-1244682887

### CODE REVIEW

**Comment by bennothommo** [comment]
Note that the syntax used here will make the original framework unable to work with Internet Explorer 11 any longer (it works with every other browser version released in the last 5-6 years).

I'm OK with this, especially if this fix is only deployed for the 1.2 branch, but worth noting anyway.

**Comment by LukeTowers** [comment]
@bennothommo I can be fine with dropping IE 11 as well, but can we add a unit test for this change so that it doesn't come up again in the future?

**Comment by bennothommo** [comment]
@LukeTowers I'm happy to take a crack at the unit test in another PR. I need this fix now (the bug it fixes messed up one of my client sites today).

**Comment by LukeTowers** [comment]
Works for me, feel free to merge it

**Pull request merged**
