### PR TITLE
Populate the form fields values.

### PR DESCRIPTION
**Pull request by mjauvin**
Replaces https://github.com/wintercms/winter/pull/1126

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin is there any chance you could add a unit test that could cover all of the issues we've encountered with this change? (just interacting with the Form widget & some models directly)

**Comment by mjauvin** [comment]
@LukeTowers I'd like to, but I'm not sure I know how to do this.

**Comment by LukeTowers** [comment]
@mjauvin are you able to start just by listing out all the problems we've had (starting with the first issue that caused us to want to apply it in multiple locations) describing the original issue, what should have happened, what did happen, and what we did to fix the issue? I should be able to turn those into some unit tests.

**Comment by mjauvin** [comment]
@LukeTowers

Initial PR #927 fixed #950:
When you define a hidden field you want to show in the filterFields() model method, the later is not correctly saved.
This behavior occurs because the model form fields filtering is not applied in the getSaveData() widget method.

PR #1099 Fixed #1036:
Try to access a model attribute via `$this` (e.g. `$this->someAttribute`) in the `filterFields()` method. Before v1.2.4 the model attributes are populated but after v1.2.4 they are all null.

**Comment by mjauvin** [comment]
@LukeTowers just realized this PR probably breaks #950 ...

**Comment by mjauvin** [comment]
> @LukeTowers just realized this PR probably breaks #950 ...

Just tested it and I was right... I really don't know how to solve all cases here...

**Comment by mjauvin** [comment]
I'd really like to know why the form fields AND the model fields are set when `filterFields` gets called in the Form widget's `onRefresh()` but not in the FormController's `create_onSave()` ... there lies the solution to this issue.

**Comment by mjauvin** [comment]
@LukeTowers I tried many different scenarios and the safest is to revert the changes to `Widgets\Form::getSaveData()`

**Comment by mjauvin** [comment]
@LukeTowers @bennothommo @jaxwilko  this is the most promissing fix yet.

If there is no objections from you guys in calling `$this->formWidget->setFormValues()` from within the FormController's `create_onSave / update_onSave` methods, this should resolve all issues.

**Comment by bennothommo** [comment]
@mjauvin I have no objections if it works, just need to test it in a variety of contexts to make sure it doesn't break something :)

**Comment by LukeTowers** [comment]
I'll review this and see if I can build out some tests, I don't want to have to come back to this again.

**Comment by mjauvin** [comment]
@LukeTowers I am still getting a case where having the `applyFiltersFromModel()` method called in `getSaveData()` creates an issue when saving a new form.

I surrender, strongly suggest we avoid calling this as done in https://github.com/wintercms/winter/pull/1126

**Comment by mjauvin** [comment]
Closing this as it does not resolve the issues.

**Pull request closed without merging**
