### PR TITLE
Mirror sqlite database file

### PR DESCRIPTION
**Pull request by mjauvin**
- added "storage/database.sqlite" to $files array
- mirror file section at the end so that sub-folders have been created at this point

### CODE REVIEW

**Comment by bennothommo** [comment]
@mjauvin What's the rationale for making the `storage/database.sqlite` file available in the public directory? That would be a huge security issue, I would think?

**Comment by mjauvin** [comment]
@bennothommo do you have another solution to make this work when using a public (winter:mirror) docroot?

If the site is using sqlite, it won't work unless the sqlite file is under public.

**Comment by bennothommo** [comment]
@mjauvin I don't understand the root issue you're trying to solve. Would you mind explaining the issue in more detail?

There is absolutely no reason for the `database.sqlite` file to be publicly accessible. That's essentially allowing anyone to simply download a copy of your database and be able to access all sorts of critical information.

**Comment by mjauvin** [comment]
@bennothommo the file won't be publicly accessible because of the .htaccess file rules, but it is needed by winter cms to render the website (frontend and backend) if your website is using sqlite db backend.

**Comment by bennothommo** [comment]
@mjauvin alright, I've managed to replicate the issue - the issue is that, by default, the `DB_DATABASE` environment variable (or the default value for `database.connnections.sqlite.database`) use a relative path to the database file. With the storage directory being mirrored, this makes the `public/storage` directory the most direct relative path, so it expects the `database.sqlite` file to be in there.

This is a configuration issue though - easily resolved by simply using an absolute path to the database file.

**Comment by mjauvin** [comment]
I confirm this, setting DB_DATABASE to the absolute path does the trick!

**Comment by LukeTowers** [comment]
@mjauvin does https://github.com/wintercms/winter/commit/0061b09246c2ed2a94cf56a81842cd35180ee4e1 solve the problem better by default?

**Comment by mjauvin** [comment]
@LukeTowers yes, that resolves the issue.

Thanks.

**Pull request closed without merging**
