### PR TITLE
Add new multilingual button css support

### PR DESCRIPTION
**Pull request by AIC-BV**
https://github.com/wintercms/wn-translate-plugin/pull/73

### CODE REVIEW

**Comment by AIC-BV** [comment]
Looking for a friendly soul to add this in the mlmarkdowneditor.js

**Comment by LukeTowers** [comment]
I'm not really a fan of requiring this in the core just to make a plugin work, why can't the plugin handle this?

**Comment by AIC-BV** [comment]
I guess it can, I was looking for a fix and the  required events are just not there (yet)

**Comment by LukeTowers** [comment]
@mjauvin can you chime in on this?

**Comment by mjauvin** [comment]
> @mjauvin can you chime in on this?

I didn't look deeply in this, but it should be possible to override the necessary code in `mlmarkdowneditor.js` in Winter.Translate

**Comment by AIC-BV** [comment]
@mjauvin can you get me started so we can finish this?
The button event is defined in `markdowneditor.js` and so are the required methods (`toggleFullscreen()` & `togglePreview()`).
It does not exist in `mlmarkdowneditor.js`

**Comment by AIC-BV** [comment]
I think I found it

**Pull request closed without merging**
