### PR TITLE
Wrong src path for Font Awesome font-face - Update modules\system\assets\css\styles.css

### PR DESCRIPTION
**Pull request by Quendi6**
Issue:
Back-end system errors pages like "Access denied" are showing unrecognized characters symbols instead of correct Font Awesome 6 icons.

Solution:
Replacing the wrong `../ui/ui/font/` source path part by `../ui/font/` in Font Awesome `@font-face`.

Result:
After this fix, there is no longer a problem with Font Awesome 6 icons in back-end system error pages.

### CODE REVIEW

**Comment by mjauvin** [comment]
This change needs to be done in the `styles.less` file and the css file needs to be recompiled with `artisan winter:util compile less`

**Comment by mjauvin** [comment]
The @font-face are actually in `ui/icons.less` but imported from `less/styles.less`

**Comment by mjauvin** [comment]
That being said, I don't recall seeing missing icons... can you describe how to reproduce this?

**Comment by Quendi6** [comment]
> This change needs to be done in the `styles.less` file and the css file needs to be recompiled with `artisan winter:util compile less`

You are right, `@font-path: "../ui/font"; // For icon fonts` show the correct path in `less/styles.less`.

But if I recompile asset bundles, I got this:
```
php artisan winter:util compile less
Compiling registered asset bundles...
builder.less
 -> /plugins/winter/builder/assets/css/builder.css
winter.less
 -> /modules/backend/assets/css/winter.css
mediamanager.less
 -> /modules/backend/widgets/mediamanager/assets/css/mediamanager.css
reportcontainer.less
 -> /modules/backend/widgets/reportcontainer/assets/css/reportcontainer.css
table.less
 -> /modules/backend/widgets/table/assets/css/table.css
codeeditor.less
 -> /modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css
repeater.less
 -> /modules/backend/formwidgets/repeater/assets/css/repeater.css
fileupload.less
 -> /modules/backend/formwidgets/fileupload/assets/css/fileupload.css
nestedform.less
 -> /modules/backend/formwidgets/nestedform/assets/css/nestedform.css
permissioneditor.less
 -> /modules/backend/formwidgets/permissioneditor/assets/css/permissioneditor.css
markdowneditor.less
 -> /modules/backend/formwidgets/markdowneditor/assets/css/markdowneditor.css
winter.components.less
 -> /modules/cms/assets/css/winter.components.css
winter.theme-selector.less
 -> /modules/cms/assets/css/winter.theme-selector.css
assetlist.less
 -> /modules/cms/widgets/assetlist/assets/css/assetlist.css
```

No `style.css` was recompiled...

**Comment by Quendi6** [comment]
> That being said, I don't recall seeing missing icons... can you describe how to reproduce this?

One way I have found is to try to access a backend page that you are not authorized to view, by impersonating a low permissions user if you are superuser.

Another way is to create an error that will trigger the correct error page if you are in debug mode, like this :
image

**Comment by Quendi6** [comment]
You are right, my commit is not exactly the right solution. But we need to provide a correct `style.css` inside the repository.

Now we also need `php artisan winter:util compile less` command to compile less files in `modules\system\assets\less` folder, which doesn't seem to be the case currently.

**Comment by mjauvin** [comment]
> One way I have found is to try to access a backend page that you are not authorized to view, by impersonating a low permissions user if you are superuser.
> 
> Another way is to create an error that will trigger the correct error page if you are in debug mode

I was able to reproduce this with the above procedure.

@LukeTowers any idea ?

**Comment by LukeTowers** [comment]
@bennothommo ping

**Comment by bennothommo** [comment]
Thanks for the prod, everyone. I've fixed this in https://github.com/wintercms/winter/commit/edafa6da7ce0ed9408cce702b6fb3c9697e5e4a8.

EDIT: Sorry, @Quendi6, I meant to hat tip you in that commit for the original fix. Apologies. To clarify your comment about compiling the correct LESS file, note that that particular `style.less` file is being compiled by Mix now, so the command would be `php artisan mix:compile --production -p module-system` (after running `php artisan mix:install`, of course).

**Comment by Quendi6** [comment]
@bennothommo No problem. Thank you the explanation.

**Comment by Quendi6** [comment]
`css/styles.css` seems okay with `../ui/font/`. `php artisan mix:compile --production -p module-system` work fine after `less/styles.less` change.

But I see a new file `less/styles.css` with a wrong path `../font/` 😕

**Comment by bennothommo** [comment]
Whoops, that would be my VSCode trying to be too clever.

**Pull request closed without merging**
