### PR TITLE
Support for plugins with versions that start with a "V"

### PR DESCRIPTION
**Pull request by multiwebinc**
Proposed fix for #466

<a href="https://gitpod.io/#https://github.com/wintercms/winter/pull/468"></a>

### CODE REVIEW

**Comment by LukeTowers** [comment]
@multiwebinc thanks for the contribution, apologies for the delay in reviewing it. Would you be willing to add some test cases for this to the testing suite?

**Comment by multiwebinc** [comment]
@LukeTowers How are tests typically executed? If I do `php artisan winter:test`, I just get a whole bunch of errors (257/267 tests errored).

**Comment by LukeTowers** [comment]
hmm @multiwebinc, that's odd. What version of Winter are you running? What are the errors complaining about? What version of PHP are you using? What operating system?

**Comment by multiwebinc** [comment]
@LukeTowers It looks like the errors are all 

```
Error: Cannot use object of type Winter\Storm\Support\Facades\Config as array

/path/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:334
/path/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:58
/path/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:71
/path/vendor/winter/storm/src/Halcyon/Model.php:1557
/path/vendor/winter/storm/src/Halcyon/HalcyonServiceProvider.php:38
/path/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:616
/path/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:75
/path/vendor/winter/storm/src/Foundation/Application.php:401
/path/vendor/winter/storm/src/Foundation/Application.php:409
/path/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
/path/vendor/winter/storm/src/Foundation/Application.php:127
/path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:320
/path/tests/TestCase.php:13
/path/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:102
/path/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:81
phpvfscomposer:///path/vendor/phpunit/phpunit/phpunit:97
```

or 

```
InvalidArgumentException: Database (storage/database.sqlite) does not exist.

/path/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34
/path/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:220
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:924
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:404
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:330
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:662
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:629
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:338
/path/vendor/laravel/framework/src/Illuminate/Database/Connection.php:309
/path/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:75
/path/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/path/modules/system/classes/UpdateManager.php:135
/path/modules/system/console/WinterUp.php:46
/path/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/path/vendor/laravel/framework/src/Illuminate/Container/Util.php:37
/path/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/path/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
/path/vendor/laravel/framework/src/Illuminate/Container/Container.php:590
/path/vendor/laravel/framework/src/Illuminate/Console/Command.php:134
/path/vendor/symfony/console/Command/Command.php:255
/path/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
/path/vendor/symfony/console/Application.php:1009
/path/vendor/symfony/console/Application.php:273
/path/vendor/symfony/console/Application.php:149
/path/vendor/laravel/framework/src/Illuminate/Console/Application.php:93
/path/vendor/laravel/framework/src/Illuminate/Console/Application.php:185
/path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:273
/path/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/path/tests/PluginTestCase.php:121
/path/tests/PluginTestCase.php:86
phpvfscomposer:///path/vendor/phpunit/phpunit/phpunit:97
```

Winter build:
```
$ php artisan winter:version --changes
*** Detecting Winter CMS build...
*** Detected a modified version of Winter CMS build 1.1.8.

We have detected the following modifications:

Files added:
 - /modules/system/.eslintignore
 - /modules/system/.eslintrc.json
 - /modules/system/.gitignore
 - /modules/system/assets/js/build/manifest.js
 - /modules/system/assets/js/build/system.js
 - /modules/system/assets/js/build/vendor.js
 - /modules/system/assets/js/snowboard/build/snowboard.vendor.js
 - /modules/system/assets/js/snowboard/utilities/Url.js
 - /modules/system/console/MixUpdate.php
 - /modules/system/package.json
 - /modules/system/winter.mix.js

Files modified:
 - /modules/system/ServiceProvider.php
 - /modules/system/assets/css/snowboard.extras.css
 - /modules/system/assets/js/snowboard/ajax/Request.js
 - /modules/system/assets/js/snowboard/ajax/handlers/AttributeRequest.js
 - /modules/system/assets/js/snowboard/build/snowboard.base.debug.js
 - /modules/system/assets/js/snowboard/build/snowboard.base.js
 - /modules/system/assets/js/snowboard/build/snowboard.data-attr.js
 - /modules/system/assets/js/snowboard/build/snowboard.extras.js
 - /modules/system/assets/js/snowboard/build/snowboard.request.js
 - /modules/system/assets/js/snowboard/extras/Flash.js
 - /modules/system/assets/js/snowboard/extras/StylesheetLoader.js
 - /modules/system/assets/js/snowboard/main/PluginLoader.js
 - /modules/system/assets/js/snowboard/main/Snowboard.js
 - /modules/system/assets/js/snowboard/snowboard.extras.js
 - /modules/system/assets/less/snowboard.extras.less
 - /modules/system/classes/PluginManager.php
 - /modules/system/classes/UpdateManager.php
 - /modules/system/composer.json
 - /modules/system/console/MixCompile.php
 - /modules/system/console/MixInstall.php
 - /modules/system/views/maintenance.php
 - /modules/backend/composer.json
 - /modules/backend/formwidgets/Repeater.php
 - /modules/backend/formwidgets/repeater/assets/js/repeater.js
 - /modules/backend/formwidgets/repeater/partials/_repeater.htm
 - /modules/backend/formwidgets/repeater/partials/_repeater_item.htm
 - /modules/backend/lang/de/lang.php
 - /modules/backend/layouts/_head.htm
 - /modules/cms/classes/Controller.php
 - /modules/cms/composer.json
 - /modules/cms/twig/SnowboardNode.php

Files removed:
 - 0
 - 1
 - 2
 - 3
 - 4

```

PHP 7.4.3 on Ubuntu

**Comment by LukeTowers** [comment]
@bennothommo @jaxwilko any ideas?

**Comment by bennothommo** [comment]
@LukeTowers @multiwebinc doesn't seem to happen for me on a fresh copy. I do see errors happen during testing if I have an environment file in the project I'm testing and I'm using SQLite.

Perhaps try the tests on a fresh copy.

**Comment by LukeTowers** [comment]
@multiwebinc is this fixed in the 1.2 branch? See https://github.com/wintercms/winter/commit/af311f7001d9f07c802166faafaa0d5715a2dc78

**Comment by multiwebinc** [comment]
@LukeTowers Yes, this was fixed in https://github.com/wintercms/winter/commit/af311f7001d9f07c802166faafaa0d5715a2dc78 as you mentioned in https://github.com/wintercms/winter/issues/466#issuecomment-1166196958. I guess you can feel free to close this PR.

**Pull request closed without merging**
