### PR TITLE
Return correct URLs from File->getPublicPath for non-local disks

### PR DESCRIPTION
**Pull request by wpjscc**
when driver is cloud driver, the url  is dependent on ASSET_URL。

it should dependent on cloud ENDPOINT

### CODE REVIEW

**Comment by bennothommo** [comment]
I think there's a specific rationale for why it's like that - @jaxwilko or @LukeTowers might know more.

**Comment by jaxwilko** [comment]
@bennothommo I vaguly remember it being important, not sure why though. In theory this change looks okay but maybe @LukeTowers knows more

**Comment by LukeTowers** [comment]
Hmm, on my phone at the moment but check the git blame. Hopefully there's a decent commit message

**Comment by bennothommo** [comment]
https://github.com/wintercms/winter/commit/5aa351f67c0f9b4d7b1b5c5cb6c2199d19164c79

Not sure about that...

**Comment by LukeTowers** [comment]
This is totally fine then @bennothommo, that commit is from before I added the getDisk() method to the File model in https://github.com/wintercms/storm/commit/48fed9b7e4c4c22ccc6b3c2e5b1273da3e2c38dd, just leftover code from the old non-disk focused way of doing things.

**Pull request merged**
