### PR TITLE
Enable framework extras in backend

### LINKED ISSUE #1233: Framework extras missing in backend
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

_No response_

### Issue description

Trying to use a button in a backend view with a `data-attach-loading` does not work. 

Note: this works fine on a frontend page

### Steps to replicate

Add the following button to a backend controller:
```html
<button data-attach-loading data-request=onAjax>TEST</button>
```

### Workaround

_No response_

### PR DESCRIPTION
**Pull request by mjauvin**
Fixes #1233

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin does this cause any duplication / double handling of existing backend functionality?

**Comment by mjauvin** [comment]
@LukeTowers I checked thoroughly and there is no duplication whatsoever.

**Comment by mjauvin** [comment]
I just realized there may be a need to also include the extras css as well... will check asap and report back here.

**Comment by mjauvin** [comment]
Ok, so the extras styles are already contained in `snowboard.extras.css`, so no need here.

**Comment by mjauvin** [comment]
@bennothommo what was the reason you included `snowboard.extras.css` in the backend ?

**Comment by bennothommo** [comment]
@mjauvin the backend build of Snowboard does use some utilities that need styling (Flash, Stripe Loader, Transition).

Also, I'm thinking it might be better that we try and hook up the original AJAX framework's events to Snowboard, and use the Snowboard Attach Loading utility instead. Should hopefully be doable.

**Comment by bennothommo** [comment]
I've submitted an alternate way of handling this - #1235. I've seen one plugin manually including the `framework.extras` (Test plugin), so I'm leaning towards it was only meant to be included when needed and not globally, but up to you guys if we want to hook it into Snowboard or just use @mjauvin's PR.

**Comment by LukeTowers** [comment]
@jaxwilko any thoughts?

**Comment by mjauvin** [comment]
replaced by #1235

**Pull request closed without merging**
