### PR TITLE
Fix image resizer folder/file permissions

### PR DESCRIPTION
**Pull request by mjauvin**
Fixes https://github.com/wintercms/winter/issues/503

Least favorite solution, only fixes the image resizer.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@jaxwilko are there any concerns about adding these attributes when the resized disk is set to S3 or any other remote storage?

**Comment by jaxwilko** [comment]
Will this generate public thumbnails for protected items?

Apart from that i don't think so but i will do a proper test with s3 tonight :)

**Comment by mjauvin** [comment]
@LukeTowers what about applying this change only `if $disk->getDriver() === 'local'` ?

**Comment by LukeTowers** [comment]
Closing in favour of https://github.com/wintercms/storm/pull/92

**Pull request closed without merging**
